# One CLI to format the code tree - https://github.com/numtide/treefmt
excludes = ["*.toml"]

[formatter.yamlfmt]
command = "yamlfmt"
includes = ["*.yaml"]

[formatter.nixfmt]
command = "nixfmt"
includes = ["*.nix"]
